// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogHubDocumentDataSlicesSlice =
	| RssBlockSlice
	| HeroSlice
	| BreadcrumbsSlice
	| VideoSlice
	| BlankSpaceSlice
	| CardsSlice
	| ManualBlogBlockSlice;

/**
 * Content for Blog Hub documents
 */
interface BlogHubDocumentData {
	/**
	 * Slice Zone field in *Blog Hub*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_hub.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone /**
	 * Meta Description field in *Blog Hub*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blog_hub.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Title field in *Blog Hub*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blog_hub.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField /**
	 * Head field in *Blog Hub*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_hub.head
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */;
	head: prismic.RichTextField;

	/**
	 * Body field in *Blog Hub*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_hub.body
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Blog Hub document from Prismic
 *
 * - **API ID**: `blog_hub`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHubDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID;

type CollectionDocumentDataSlicesSlice =
	| BlankSpaceSlice
	| BreadcrumbsSlice
	| CollectionProductCardSlice;

/**
 * Content for Collection documents
 */
interface CollectionDocumentData {
	/**
	 * Slice Zone field in *Collection*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone /**
	 * Meta Description field in *Collection*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: collection.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Title field in *Collection*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: collection.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField /**
	 * Head field in *Collection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection.head
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */;
	head: prismic.RichTextField;

	/**
	 * Body field in *Collection*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection.body
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID;

/**
 * Item in *Layout → Links*
 */
export interface LayoutDocumentDataLinksItem {
	/**
	 * Label field in *Layout → Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Layout → Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Layout → Links Group 1*
 */
export interface LayoutDocumentDataLinksGroup1Item {
	/**
	 * Label field in *Layout → Links Group 1*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_1[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Layout → Links Group 1*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_1[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Layout → Links Group 2*
 */
export interface LayoutDocumentDataLinksGroup2Item {
	/**
	 * Label field in *Layout → Links Group 2*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_2[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Layout → Links Group 2*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_2[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Layout → Links Group 3*
 */
export interface LayoutDocumentDataLinksGroup3Item {
	/**
	 * Label field in *Layout → Links Group 3*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_3[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Layout → Links Group 3*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_3[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Layout → Social Links*
 */
export interface LayoutDocumentDataSocialLinksItem {
	/**
	 * Link field in *Layout → Social Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.social_links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Icon field in *Layout → Social Links*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.social_links[].icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField;
}

/**
 * Item in *Layout → Gallery*
 */
export interface LayoutDocumentDataGalleryItem {
	/**
	 * Image field in *Layout → Gallery*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.gallery[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;
}

/**
 * Item in *Layout → Prompt Suggestions*
 */
export interface LayoutDocumentDataPromptSuggestionsItem {
	/**
	 * Prompt field in *Layout → Prompt Suggestions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.prompt_suggestions[].prompt
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	prompt: prismic.KeyTextField;
}

/**
 * Item in *Layout → Style Presets*
 */
export interface LayoutDocumentDataStylePresetsItem {
	/**
	 * Name field in *Layout → Style Presets*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.style_presets[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Prefix field in *Layout → Style Presets*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.style_presets[].prefix
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	prefix: prismic.KeyTextField;

	/**
	 * Suffix field in *Layout → Style Presets*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.style_presets[].suffix
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	suffix: prismic.KeyTextField;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
	/**
	 * Notice field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.notice
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	notice: prismic.RichTextField /**
	 * Logo field in *Layout*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.logo
	 * - **Tab**: Header
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */;
	logo: prismic.ImageField;

	/**
	 * Links field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links[]
	 * - **Tab**: Header
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField;

	/**
	 * Account Link field in *Layout*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.account_link
	 * - **Tab**: Header
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	account_link: prismic.LinkField /**
	 * Footer Logo field in *Layout*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.footer_logo
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */;
	footer_logo: prismic.ImageField;

	/**
	 * Links Group 1 field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_1[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links_group_1: prismic.GroupField;

	/**
	 * Links Group 2 field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_2[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links_group_2: prismic.GroupField;

	/**
	 * Links Group 3 field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.links_group_3[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links_group_3: prismic.GroupField;

	/**
	 * Social Links field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.social_links[]
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	social_links: prismic.GroupField;

	/**
	 * Klaviyo Form Embed field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.klaviyo_form_embed
	 * - **Tab**: Footer
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	klaviyo_form_embed: prismic.RichTextField /**
	 * Head field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.head
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */;
	head: prismic.RichTextField;

	/**
	 * Body field in *Layout*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.body
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField /**
	 * Gallery field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.gallery[]
	 * - **Tab**: Designer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */;
	gallery: prismic.GroupField;

	/**
	 * Prompt Suggestions field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.prompt_suggestions[]
	 * - **Tab**: Designer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	prompt_suggestions: prismic.GroupField;

	/**
	 * Style Presets field in *Layout*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: layout.style_presets[]
	 * - **Tab**: Designer
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	style_presets: prismic.GroupField /**
	 * Aspect Ratio (Front) field in *Layout*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1:1
	 * - **API ID Path**: layout.aspect_ratio_front
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */;
	aspect_ratio_front: prismic.SelectField;

	/**
	 * Aspect Ratio (Back) field in *Layout*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1:1
	 * - **API ID Path**: layout.aspect_ratio_back
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	aspect_ratio_back: prismic.SelectField;

	/**
	 * Output Quality field in *Layout*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Enter a value 1 - 100
	 * - **API ID Path**: layout.output_quality
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	output_quality: prismic.NumberField;

	/**
	 * Seed field in *Layout*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Random value by default. Use a number for seed value.
	 * - **API ID Path**: layout.seed
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	seed: prismic.NumberField;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID;

type PageDocumentDataSlicesSlice =
	| IframeEmbedSlice
	| CustomEmbedSlice
	| GallerySlice
	| AccordionsSlice
	| ContentBodySlice
	| BreadcrumbsSlice
	| BlankSpaceSlice
	| VideoSlice
	| CardsSlice
	| HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone /**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField /**
	 * Head field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.head
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */;
	head: prismic.RichTextField;

	/**
	 * Body field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.body
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID;

type PostDocumentDataSlicesSlice = BreadcrumbsSlice | CardsSlice | ContentBodySlice | HeroSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
	/**
	 * Auto RSS field in *Post*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: post.auto_rss
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	auto_rss: prismic.BooleanField;

	/**
	 * Slice Zone field in *Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone /**
	 * Meta Description field in *Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: post.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Title field in *Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: post.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField /**
	 * Head field in *Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.head
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */;
	head: prismic.RichTextField;

	/**
	 * Body field in *Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: post.body
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID;

/**
 * Item in *Product → Product Details*
 */
export interface ProductDocumentDataProductDetailsItem {
	/**
	 * Heading field in *Product → Product Details*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product_details[].heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Content field in *Product → Product Details*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product_details[].content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Item in *Product → Reviews*
 */
export interface ProductDocumentDataReviewsItem {
	/**
	 * User Name field in *Product → Reviews*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.reviews[].user_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	user_name: prismic.KeyTextField;

	/**
	 * Title field in *Product → Reviews*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.reviews[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Review field in *Product → Reviews*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.reviews[].review
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	review: prismic.RichTextField;
}

type ProductDocumentDataSlicesSlice = CardsSlice | BreadcrumbsSlice | BlankSpaceSlice;

/**
 * Item in *Product → Front*
 */
export interface ProductDocumentDataFrontItem {
	/**
	 * Property field in *Product → Front*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.front[].property
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	property: prismic.KeyTextField;

	/**
	 * Value field in *Product → Front*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.front[].value
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	value: prismic.KeyTextField;
}

/**
 * Item in *Product → Back*
 */
export interface ProductDocumentDataBackItem {
	/**
	 * Property field in *Product → Back*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.back[].property
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	property: prismic.KeyTextField;

	/**
	 * Value field in *Product → Back*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.back[].value
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	value: prismic.KeyTextField;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
	/**
	 * Product field in *Product*
	 *
	 * - **Field Type**: Integration Fields (Catalog: `randomai-10--products`)
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#integration
	 */
	product: prismic.IntegrationField;

	/**
	 * Is it a pre-designed product field in *Product*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: product.is_predesigned
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_predesigned: prismic.BooleanField;

	/**
	 * Review Stars field in *Product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.review_stars
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	review_stars: prismic.ImageField;

	/**
	 * Review Stars Text field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.review_stars_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	review_stars_text: prismic.KeyTextField;

	/**
	 * Reviews Link field in *Product*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.reviews_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	reviews_link: prismic.LinkField;

	/**
	 * Placeholder Sicker field in *Product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.placeholder_sicker
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	placeholder_sicker: prismic.ImageField;

	/**
	 * Product Details field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.product_details[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	product_details: prismic.GroupField;

	/**
	 * Reviews field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.reviews[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	reviews: prismic.GroupField;

	/**
	 * Slice Zone field in *Product*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone /**
	 * Meta Description field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: product.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Title field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: product.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField /**
	 * Head field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.head
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */;
	head: prismic.RichTextField;

	/**
	 * Body field in *Product*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.body
	 * - **Tab**: Custom Code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField /**
	 * Enable Front Canvas? field in *Product*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: product.is_front_canvas_enabled
	 * - **Tab**: Canvas Settings
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */;
	is_front_canvas_enabled: prismic.BooleanField;

	/**
	 * Enable Back Canvas? field in *Product*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: product.is_back_canvas_enabled
	 * - **Tab**: Canvas Settings
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_back_canvas_enabled: prismic.BooleanField;

	/**
	 * Front field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.front[]
	 * - **Tab**: Canvas Settings
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	front: prismic.GroupField;

	/**
	 * Back field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.back[]
	 * - **Tab**: Canvas Settings
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	back: prismic.GroupField /**
	 * Aspect Ratio (Front) field in *Product*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1:1
	 * - **API ID Path**: product.aspect_ratio_front
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */;
	aspect_ratio_front: prismic.SelectField;

	/**
	 * Aspect Ratio (Back) field in *Product*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1:1
	 * - **API ID Path**: product.aspect_ratio_back
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	aspect_ratio_back: prismic.SelectField;

	/**
	 * Output Quality field in *Product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Enter a value 1 - 100
	 * - **API ID Path**: product.output_quality
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	output_quality: prismic.NumberField;

	/**
	 * Seed field in *Product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Random value by default. Use a number for seed value.
	 * - **API ID Path**: product.seed
	 * - **Tab**: AI Settings
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	seed: prismic.NumberField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID;

export type AllDocumentTypes =
	| BlogHubDocument
	| CollectionDocument
	| LayoutDocument
	| PageDocument
	| PostDocument
	| ProductDocument;

/**
 * Primary content in *Accordions → Default → Primary*
 */
export interface AccordionsSliceDefaultPrimary {
	/**
	 * Narrow field in *Accordions → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: accordions.default.primary.is_narrow
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_narrow: prismic.BooleanField;
}

/**
 * Primary content in *Accordions → Items*
 */
export interface AccordionsSliceDefaultItem {
	/**
	 * Heading field in *Accordions → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordions.items[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Content field in *Accordions → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordions.items[].content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for Accordions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionsSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *Accordions*
 */
type AccordionsSliceVariation = AccordionsSliceDefault;

/**
 * Accordions Shared Slice
 *
 * - **API ID**: `accordions`
 * - **Description**: Accordions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionsSlice = prismic.SharedSlice;

/**
 * Primary content in *BlankSpace → Default → Primary*
 */
export interface BlankSpaceSliceDefaultPrimary {
	/**
	 * Size field in *BlankSpace → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Small
	 * - **API ID Path**: blank_space.default.primary.size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	size: prismic.SelectField;
}

/**
 * Default variation for BlankSpace Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlankSpaceSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *BlankSpace*
 */
type BlankSpaceSliceVariation = BlankSpaceSliceDefault;

/**
 * BlankSpace Shared Slice
 *
 * - **API ID**: `blank_space`
 * - **Description**: BlankSpace
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlankSpaceSlice = prismic.SharedSlice;

/**
 * Primary content in *Breadcrumbs → Items*
 */
export interface BreadcrumbsSliceDefaultItem {
	/**
	 * Link field in *Breadcrumbs → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: breadcrumbs.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Text field in *Breadcrumbs → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: breadcrumbs.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;
}

/**
 * Default variation for Breadcrumbs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BreadcrumbsSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *Breadcrumbs*
 */
type BreadcrumbsSliceVariation = BreadcrumbsSliceDefault;

/**
 * Breadcrumbs Shared Slice
 *
 * - **API ID**: `breadcrumbs`
 * - **Description**: Breadcrumbs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BreadcrumbsSlice = prismic.SharedSlice;

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
	/**
	 * Eyebrow Headline field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image should cover? field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards.default.primary.is_cover
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_cover: prismic.BooleanField;

	/**
	 * Use 4 columns for on Desktop? field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards.default.primary.is_4_col_layout
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_4_col_layout: prismic.BooleanField;

	/**
	 * Contained? field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: cards.default.primary.is_contained
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_contained: prismic.BooleanField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceDefaultItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Title field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Link field in *Cards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Subtext field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Tags field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Comma seperated values e.g (tag-1, tag-2) etc
	 * - **API ID Path**: cards.items[].tags
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tags: prismic.KeyTextField;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation;

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceCards2ColumnsBigItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Link field in *Cards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Button Text field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;
}

/**
 * Cards - 2 Columns Big variation for Cards Slice
 *
 * - **API ID**: `cards2ColumnsBig`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCards2ColumnsBig = prismic.SharedSliceVariation;

/**
 * Primary content in *Cards → Cards - With Color Toggle → Primary*
 */
export interface CardsSliceCardsWithColorTogglePrimary {
	/**
	 * Eyebrow Headline field in *Cards → Cards - With Color Toggle → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsWithColorToggle.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Cards → Cards - With Color Toggle → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsWithColorToggle.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Cards → Cards - With Color Toggle → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsWithColorToggle.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Button Text field in *Cards → Cards - With Color Toggle → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsWithColorToggle.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * Link field in *Cards → Cards - With Color Toggle → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsWithColorToggle.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceCardsWithColorToggleItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Swatches Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].swatches_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	swatches_image: prismic.ImageField;

	/**
	 * Title field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Link field in *Cards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Subtext field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Review Text field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].review_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	review_text: prismic.RichTextField;
}

/**
 * Cards - With Color Toggle variation for Cards Slice
 *
 * - **API ID**: `cardsWithColorToggle`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCardsWithColorToggle = prismic.SharedSliceVariation;

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceCardsReviewsItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Name field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.RichTextField;

	/**
	 * Description field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Cards - Reviews variation for Cards Slice
 *
 * - **API ID**: `cardsReviews`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCardsReviews = prismic.SharedSliceVariation;

/**
 * Primary content in *Cards → Cards - Dual Column → Primary*
 */
export interface CardsSliceCardsDualColumnPrimary {
	/**
	 * Eyebrow Headline field in *Cards → Cards - Dual Column → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsDualColumn.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Cards → Cards - Dual Column → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsDualColumn.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Cards → Cards - Dual Column → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsDualColumn.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Link field in *Cards → Cards - Dual Column → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsDualColumn.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Button Text field in *Cards → Cards - Dual Column → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsDualColumn.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceCardsDualColumnItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Title field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Link field in *Cards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Subtext field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Button Text field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;
}

/**
 * Cards - Dual Column variation for Cards Slice
 *
 * - **API ID**: `cardsDualColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCardsDualColumn = prismic.SharedSliceVariation;

/**
 * Primary content in *Cards → Cards - List Layout → Primary*
 */
export interface CardsSliceCardsListLayoutPrimary {
	/**
	 * Eyebrow Headline field in *Cards → Cards - List Layout → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsListLayout.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Cards → Cards - List Layout → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsListLayout.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Cards → Cards - List Layout → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsListLayout.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceCardsListLayoutItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Title field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Link field in *Cards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Subtext field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Button Text field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * Tag field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].tag
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tag: prismic.KeyTextField;

	/**
	 * Publisher Name field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].publisher_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	publisher_name: prismic.KeyTextField;

	/**
	 * Published Date field in *Cards → Items*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].published_date
	 * - **Documentation**: https://prismic.io/docs/field#timestamp
	 */
	published_date: prismic.TimestampField;
}

/**
 * Cards - List Layout variation for Cards Slice
 *
 * - **API ID**: `cardsListLayout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCardsListLayout = prismic.SharedSliceVariation;

/**
 * Primary content in *Cards → Cards - Flat List → Primary*
 */
export interface CardsSliceCardsFlatListPrimary {
	/**
	 * Eyebrow Headline field in *Cards → Cards - Flat List → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsFlatList.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Cards → Cards - Flat List → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsFlatList.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Cards → Cards - Flat List → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.cardsFlatList.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardsSliceCardsFlatListItem {
	/**
	 * Image field in *Cards → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Title field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Link field in *Cards → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Subtext field in *Cards → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Button Text field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * Tag field in *Cards → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.items[].tag
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tag: prismic.KeyTextField;
}

/**
 * Cards - Flat List variation for Cards Slice
 *
 * - **API ID**: `cardsFlatList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCardsFlatList = prismic.SharedSliceVariation;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation =
	| CardsSliceDefault
	| CardsSliceCards2ColumnsBig
	| CardsSliceCardsWithColorToggle
	| CardsSliceCardsReviews
	| CardsSliceCardsDualColumn
	| CardsSliceCardsListLayout
	| CardsSliceCardsFlatList;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice;

/**
 * Primary content in *CollectionProductCard → Default → Primary*
 */
export interface CollectionProductCardSliceDefaultPrimary {
	/**
	 * Product field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Integration Fields (Catalog: `randomai-10--products`)
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.product
	 * - **Documentation**: https://prismic.io/docs/field#integration
	 */
	product: prismic.IntegrationField;

	/**
	 * Link field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Link Text field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	link_text: prismic.RichTextField;

	/**
	 * Review Text field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.review_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	review_text: prismic.KeyTextField;

	/**
	 * Gender field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.gender
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	gender: prismic.KeyTextField;

	/**
	 * Collection field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.collection
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	collection: prismic.KeyTextField;

	/**
	 * Brand field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.brand
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	brand: prismic.KeyTextField;

	/**
	 * Product field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.product_type
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	product_type: prismic.KeyTextField;

	/**
	 * Review Stars field in *CollectionProductCard → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.default.primary.review_stars
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	review_stars: prismic.ImageField;
}

/**
 * Primary content in *CollectionProductCard → Items*
 */
export interface CollectionProductCardSliceDefaultItem {
	/**
	 * Image field in *CollectionProductCard → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Swatch field in *CollectionProductCard → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.items[].swatch
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	swatch: prismic.ImageField;

	/**
	 * Color Name field in *CollectionProductCard → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: collection_product_card.items[].color_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	color_name: prismic.KeyTextField;
}

/**
 * Default variation for CollectionProductCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionProductCardSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *CollectionProductCard*
 */
type CollectionProductCardSliceVariation = CollectionProductCardSliceDefault;

/**
 * CollectionProductCard Shared Slice
 *
 * - **API ID**: `collection_product_card`
 * - **Description**: CollectionProductCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionProductCardSlice = prismic.SharedSlice;

/**
 * Primary content in *ContentBody → Default → Primary*
 */
export interface ContentBodySliceDefaultPrimary {
	/**
	 * Title field in *ContentBody → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_body.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Content field in *ContentBody → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_body.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Narrow? field in *ContentBody → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: content_body.default.primary.is_narrow
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_narrow: prismic.BooleanField;
}

/**
 * Primary content in *ContentBody → Items*
 */
export interface ContentBodySliceDefaultItem {
	/**
	 * Image field in *ContentBody → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_body.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Text Content field in *ContentBody → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_body.items[].text_content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_content: prismic.RichTextField;
}

/**
 * Default variation for ContentBody Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBodySliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *ContentBody*
 */
type ContentBodySliceVariation = ContentBodySliceDefault;

/**
 * ContentBody Shared Slice
 *
 * - **API ID**: `content_body`
 * - **Description**: ContentBody
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBodySlice = prismic.SharedSlice;

/**
 * Primary content in *CustomEmbed → Default → Primary*
 */
export interface CustomEmbedSliceDefaultPrimary {
	/**
	 * Heading field in *CustomEmbed → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: custom_embed.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Subtext field in *CustomEmbed → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: custom_embed.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Embed field in *CustomEmbed → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: custom_embed.default.primary.embed
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	embed: prismic.RichTextField;
}

/**
 * Default variation for CustomEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomEmbedSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *CustomEmbed*
 */
type CustomEmbedSliceVariation = CustomEmbedSliceDefault;

/**
 * CustomEmbed Shared Slice
 *
 * - **API ID**: `custom_embed`
 * - **Description**: CustomEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomEmbedSlice = prismic.SharedSlice;

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
	/**
	 * Heading field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Subtext field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
	/**
	 * Image field in *Gallery → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Title field in *Gallery → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Description field in *Gallery → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Eyebrow Headline field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Primary Button Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.primary_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	primary_button_text: prismic.KeyTextField;

	/**
	 * Primary Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.primary_button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	primary_button_link: prismic.LinkField;

	/**
	 * Secondary Button Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.secondary_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	secondary_button_text: prismic.KeyTextField;

	/**
	 * Secondary Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.secondary_button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	secondary_button_link: prismic.LinkField;

	/**
	 * Set Background to Gray? field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.is_bg_gray
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_bg_gray: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation;

/**
 * Primary content in *Hero → With Image Generator → Primary*
 */
export interface HeroSliceWithImageGeneratorPrimary {
	/**
	 * Eyebrow Headline field in *Hero → With Image Generator → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withImageGenerator.primary.eyebrow_headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	eyebrow_headline: prismic.RichTextField;

	/**
	 * Heading field in *Hero → With Image Generator → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withImageGenerator.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Hero → With Image Generator → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withImageGenerator.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Set Background to Gray? field in *Hero → With Image Generator → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.withImageGenerator.primary.is_bg_gray
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_bg_gray: prismic.BooleanField;

	/**
	 * Link Label field in *Hero → With Image Generator → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withImageGenerator.primary.link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_label: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceWithImageGeneratorItem {
	/**
	 * Image field in *Hero → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField;

	/**
	 * Top field in *Hero → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].top
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	top: prismic.KeyTextField;

	/**
	 * Left field in *Hero → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].left
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	left: prismic.KeyTextField;

	/**
	 * Height field in *Hero → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].height
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	height: prismic.KeyTextField;

	/**
	 * Width field in *Hero → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].width
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	width: prismic.KeyTextField;

	/**
	 * Editor Link field in *Hero → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].editor_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	editor_link: prismic.LinkField;
}

/**
 * With Image Generator variation for Hero Slice
 *
 * - **API ID**: `withImageGenerator`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithImageGenerator = prismic.SharedSliceVariation;

/**
 * Primary content in *Hero → For - RSS Blogs → Primary*
 */
export interface HeroSliceForRssBlogsPrimary {
	/**
	 * Heading field in *Hero → For - RSS Blogs → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.forRssBlogs.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Description field in *Hero → For - RSS Blogs → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.forRssBlogs.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Underlined? field in *Hero → For - RSS Blogs → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.forRssBlogs.primary.is_underlined
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_underlined: prismic.BooleanField;
}

/**
 * For - RSS Blogs variation for Hero Slice
 *
 * - **API ID**: `forRssBlogs`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceForRssBlogs = prismic.SharedSliceVariation;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithImageGenerator | HeroSliceForRssBlogs;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice;

/**
 * Primary content in *IframeEmbed → Default → Primary*
 */
export interface IframeEmbedSliceDefaultPrimary {
	/**
	 * Heading field in *IframeEmbed → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: iframe_embed.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Subtext field in *IframeEmbed → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: iframe_embed.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Head field in *IframeEmbed → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: iframe_embed.default.primary.head
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	head: prismic.RichTextField;

	/**
	 * Body field in *IframeEmbed → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: iframe_embed.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Minimum Height (REM) field in *IframeEmbed → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: iframe_embed.default.primary.minimum_height
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	minimum_height: prismic.KeyTextField;
}

/**
 * Default variation for IframeEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IframeEmbedSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *IframeEmbed*
 */
type IframeEmbedSliceVariation = IframeEmbedSliceDefault;

/**
 * IframeEmbed Shared Slice
 *
 * - **API ID**: `iframe_embed`
 * - **Description**: IframeEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IframeEmbedSlice = prismic.SharedSlice;

/**
 * Primary content in *ManualBlogBlock → Default → Primary*
 */
export interface ManualBlogBlockSliceDefaultPrimary {
	/**
	 * Section Heading field in *ManualBlogBlock → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Latest from Random AI
	 * - **API ID Path**: manual_blog_block.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;
}

/**
 * Primary content in *ManualBlogBlock → Items*
 */
export interface ManualBlogBlockSliceDefaultItem {
	/**
	 * Title field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: manual_blog_block.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Featured Image field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: manual_blog_block.items[].featured_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image: prismic.ImageField;

	/**
	 * Excerpt field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: manual_blog_block.items[].excerpt
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	excerpt: prismic.RichTextField;

	/**
	 * Content field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: manual_blog_block.items[].content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;

	/**
	 * Categories (comma-separated) field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: AI, Design, Tutorial
	 * - **API ID Path**: manual_blog_block.items[].categories
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	categories: prismic.KeyTextField;

	/**
	 * Author Name field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: manual_blog_block.items[].author
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	author: prismic.KeyTextField;

	/**
	 * Publish Date field in *ManualBlogBlock → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: manual_blog_block.items[].publish_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	publish_date: prismic.DateField;
}

/**
 * Default variation for ManualBlogBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ManualBlogBlockSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *ManualBlogBlock*
 */
type ManualBlogBlockSliceVariation = ManualBlogBlockSliceDefault;

/**
 * ManualBlogBlock Shared Slice
 *
 * - **API ID**: `manual_blog_block`
 * - **Description**: Display manually created blog posts in a carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ManualBlogBlockSlice = prismic.SharedSlice;

/**
 * Primary content in *RssBlock → Default → Primary*
 */
export interface RssBlockSliceDefaultPrimary {
	/**
	 * Heading field in *RssBlock → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rss_block.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Subtext field in *RssBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rss_block.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtext: prismic.RichTextField;

	/**
	 * Source RSS field in *RssBlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rss_block.default.primary.source_rss
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	source_rss: prismic.LinkField;

	/**
	 * Source Name field in *RssBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rss_block.default.primary.source_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	source_name: prismic.KeyTextField;

	/**
	 * Source Logo field in *RssBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rss_block.default.primary.source_logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	source_logo: prismic.ImageField;
}

/**
 * Default variation for RssBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RssBlockSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *RssBlock*
 */
type RssBlockSliceVariation = RssBlockSliceDefault;

/**
 * RssBlock Shared Slice
 *
 * - **API ID**: `rss_block`
 * - **Description**: RssBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RssBlockSlice = prismic.SharedSlice;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
	/**
	 * Poster field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video.default.primary.poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	poster: prismic.ImageField;

	/**
	 * Embed field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video.default.primary.embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	embed: prismic.EmbedField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice;

declare module '@prismicio/client' {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client;
	}

	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient;
	}

	interface CreateMigration {
		(): prismic.Migration;
	}

	namespace Content {
		export type {
			BlogHubDocument,
			BlogHubDocumentData,
			BlogHubDocumentDataSlicesSlice,
			CollectionDocument,
			CollectionDocumentData,
			CollectionDocumentDataSlicesSlice,
			LayoutDocument,
			LayoutDocumentData,
			LayoutDocumentDataLinksItem,
			LayoutDocumentDataLinksGroup1Item,
			LayoutDocumentDataLinksGroup2Item,
			LayoutDocumentDataLinksGroup3Item,
			LayoutDocumentDataSocialLinksItem,
			LayoutDocumentDataGalleryItem,
			LayoutDocumentDataPromptSuggestionsItem,
			LayoutDocumentDataStylePresetsItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			PostDocument,
			PostDocumentData,
			PostDocumentDataSlicesSlice,
			ProductDocument,
			ProductDocumentData,
			ProductDocumentDataProductDetailsItem,
			ProductDocumentDataReviewsItem,
			ProductDocumentDataSlicesSlice,
			ProductDocumentDataFrontItem,
			ProductDocumentDataBackItem,
			AllDocumentTypes,
			AccordionsSlice,
			AccordionsSliceDefaultPrimary,
			AccordionsSliceDefaultItem,
			AccordionsSliceVariation,
			AccordionsSliceDefault,
			BlankSpaceSlice,
			BlankSpaceSliceDefaultPrimary,
			BlankSpaceSliceVariation,
			BlankSpaceSliceDefault,
			BreadcrumbsSlice,
			BreadcrumbsSliceDefaultItem,
			BreadcrumbsSliceVariation,
			BreadcrumbsSliceDefault,
			CardsSlice,
			CardsSliceDefaultPrimary,
			CardsSliceDefaultItem,
			CardsSliceCards2ColumnsBigItem,
			CardsSliceCardsWithColorTogglePrimary,
			CardsSliceCardsWithColorToggleItem,
			CardsSliceCardsReviewsItem,
			CardsSliceCardsDualColumnPrimary,
			CardsSliceCardsDualColumnItem,
			CardsSliceCardsListLayoutPrimary,
			CardsSliceCardsListLayoutItem,
			CardsSliceCardsFlatListPrimary,
			CardsSliceCardsFlatListItem,
			CardsSliceVariation,
			CardsSliceDefault,
			CardsSliceCards2ColumnsBig,
			CardsSliceCardsWithColorToggle,
			CardsSliceCardsReviews,
			CardsSliceCardsDualColumn,
			CardsSliceCardsListLayout,
			CardsSliceCardsFlatList,
			CollectionProductCardSlice,
			CollectionProductCardSliceDefaultPrimary,
			CollectionProductCardSliceDefaultItem,
			CollectionProductCardSliceVariation,
			CollectionProductCardSliceDefault,
			ContentBodySlice,
			ContentBodySliceDefaultPrimary,
			ContentBodySliceDefaultItem,
			ContentBodySliceVariation,
			ContentBodySliceDefault,
			CustomEmbedSlice,
			CustomEmbedSliceDefaultPrimary,
			CustomEmbedSliceVariation,
			CustomEmbedSliceDefault,
			GallerySlice,
			GallerySliceDefaultPrimary,
			GallerySliceDefaultItem,
			GallerySliceVariation,
			GallerySliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceWithImageGeneratorPrimary,
			HeroSliceWithImageGeneratorItem,
			HeroSliceForRssBlogsPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceWithImageGenerator,
			HeroSliceForRssBlogs,
			IframeEmbedSlice,
			IframeEmbedSliceDefaultPrimary,
			IframeEmbedSliceVariation,
			IframeEmbedSliceDefault,
			ManualBlogBlockSlice,
			ManualBlogBlockSliceDefaultPrimary,
			ManualBlogBlockSliceDefaultItem,
			ManualBlogBlockSliceVariation,
			ManualBlogBlockSliceDefault,
			RssBlockSlice,
			RssBlockSliceDefaultPrimary,
			RssBlockSliceVariation,
			RssBlockSliceDefault,
			VideoSlice,
			VideoSliceDefaultPrimary,
			VideoSliceVariation,
			VideoSliceDefault
		};
	}
}
