// Code generated by Slice Machine. DO NOT EDIT.

import Accordions from "./Accordions/index.svelte";
import BlankSpace from "./BlankSpace/index.svelte";
import Breadcrumbs from "./Breadcrumbs/index.svelte";
import Cards from "./Cards/index.svelte";
import CollectionProductCard from "./CollectionProductCard/index.svelte";
import ContentBody from "./ContentBody/index.svelte";
import CustomEmbed from "./CustomEmbed/index.svelte";
import Gallery from "./Gallery/index.svelte";
import Hero from "./Hero/index.svelte";
import IframeEmbed from "./IframeEmbed/index.svelte";
import RssBlock from "./RssBlock/index.svelte";
import Video from "./Video/index.svelte";

export const components = {
  accordions: Accordions,
  blank_space: BlankSpace,
  breadcrumbs: Breadcrumbs,
  cards: Cards,
  collection_product_card: CollectionProductCard,
  content_body: ContentBody,
  custom_embed: CustomEmbed,
  gallery: Gallery,
  hero: Hero,
  iframe_embed: IframeEmbed,
  rss_block: RssBlock,
  video: Video
};
